---
title: "TCRView: Visualizing relationships in a comprehensive reference dataset of paired-chain T cell receptor sequences and epitope specificities"
author: "Maia Bennett-Boehm"
date: "2024-08-30"
output: html_document
---

# Paired-chain T cell receptor (TCR) reference dataset visualization

```{r setup, include=FALSE}
source("./util/library.R")
source("./util/plotting.R")
library(rstudioapi)
library(plotly)
```

```{r data-import}

# tcr.view.file <- "./paired-data/all-distinct-cdr-paired-sequences.csv"
tcr.view.file <- "./paired-data/high-confidence-paired-sequences.csv"
tcr.view.set <- read.csv(tcr.view.file)

# To make plots more legible, string wrap Epitope species values to 12 characters
tcr.view.set$Epitope.species <- str_wrap(tcr.view.set$Epitope.species, 12)

```

## Introduction: Components of the TCR:pMHC complex

```{r vj-genes}

# Datatable of VJ alleles, genes, families, with counts
vj.table <- tcr.view.set %>%
            select(clone.id, AV, AJ, BV, BJ, AV.gene, BV.gene, AJ.gene, BJ.gene, Epitope, MHC) %>%
            mutate(AV.family = ifelse(str_detect(AV.gene, "/"),
                        (str_replace_all(AV.gene, "(.*?)(/.*)", "\\1") %>%
                            str_extract("^[^\\-*]+")),
                        str_extract(AV.gene, "^[^\\-*]+")),
                    BV.family = ifelse(str_detect(BV.gene, "/"),
                        (str_replace_all(BV.gene, "(.*?)(/.*)", "\\1") %>%
                            str_extract("^[^\\-*]+")),   
                        str_extract(BV.gene, "^[^\\-*]+")),
                    AJ.family = ifelse(str_detect(AJ.gene, "/"),
                        (str_replace_all(AJ.gene, "(.*?)(/.*)", "\\1") %>%
                            str_extract("^[^\\-*]+")),
                        str_extract(AJ.gene, "^[^\\-*]+")),
                    BJ.family = ifelse(str_detect(BJ.gene, "/"),
                        (str_replace_all(BJ.gene, "(.*?)(/.*)", "\\1") %>%
                            str_extract("^[^\\-*]+")),
                        str_extract(BJ.gene, "^[^\\-*]+"))) %>%
            pivot_longer(cols = c(AV, AJ, BV, BJ), names_to = "Gene Segment", values_to = "Allele") %>%
            mutate(keep = case_when(
                `Gene Segment` == "AV" ~ "AV.gene",
                `Gene Segment` == "AJ" ~ "AJ.gene",
                `Gene Segment` == "BV" ~ "BV.gene",
                `Gene Segment` == "BJ" ~ "BJ.gene"
            )) %>%
            pivot_longer(cols = c(AV.gene, AJ.gene, BV.gene, BJ.gene), names_to = "Gene Fam. Segment", values_to = "Gene") %>%
            filter(keep == `Gene Fam. Segment`) %>%
            mutate(keep = case_when(
                `Gene Fam. Segment` == "AV.gene" ~ "AV.family",
                `Gene Fam. Segment` == "AJ.gene" ~ "AJ.family",
                `Gene Fam. Segment` == "BV.gene" ~ "BV.family",
                `Gene Fam. Segment` == "BJ.gene" ~ "BJ.family"
            )) %>%
            pivot_longer(cols = c(AV.family, AJ.family, BV.family, BJ.family), names_to = "Gene Chain", values_to = "Gene Family") %>%
            filter(keep == `Gene Chain`) %>%
            select(Allele, Gene, `Gene Family`, `Gene Segment`) %>%
            add_count(Allele, name = "Allele Count") %>%
            add_count(Gene, name = "Gene Count") %>%
            add_count(`Gene Family`, name = "Family Count") %>%
            distinct(.keep_all = TRUE) %>%
            arrange(`Gene Segment`)

datatable(vj.table, extensions=c('Scroller', 'RowGroup'), 
    options = list(dom='t', scrollX=TRUE, deferRender=TRUE, scrollY=200, scroller=TRUE, 
    rowGroup = list(dataSrc = 4), columnDefs = list(list(visible=FALSE, targets=c(4)))),
    caption="V and J gene usage in the TCR dataset")

# V J alleles (dropdown by gene)
plotVJAllele(tcr.view.set) 

# VJ genes (dropdown by gene family)
plotVJGene(tcr.view.set)

# VJ gene families
plotVJFamily(tcr.view.set)

```



```{r epitopes}

# Epitope counts table (highest to lowest abundance)
epitope.table <- tcr.view.set %>%
    select(Epitope, Epitope.gene, Epitope.species) %>%
    add_count(Epitope, name = "Epitope Count") %>%
    add_count(Epitope.gene, name = "Epitope Gene Count") %>%
    add_count(Epitope.species, name = "Epitope Species Count") %>%
    distinct(.keep_all = TRUE) %>%
    mutate(`Epitope Species` = paste0(Epitope.species, ": ", `Epitope Species Count`, " receptors")) %>%
    arrange(`Epitope Species`)

datatable(epitope.table, extensions=c('Scroller', 'RowGroup'),
    options = list(dom='t', scrollX=TRUE, deferRender=TRUE, scrollY=200, scroller=TRUE, 
    rowGroup = list(dataSrc = 7), columnDefs = list(list(visible=FALSE, targets=c(7)))),
    caption="Epitope distribution in the TCR dataset")

# Epitope count distribution
plotEpitopeCountDistribution(tcr.view.set)

# Epitope count distribution per epitope species (top 10 species, all other as "Other")
plotEpitopeCountDistributionByFactor(tcr.view.set, "Epitope.species", "Epitope Species", top = 10)

# Epitopes for top epitope species 
plotTopEpitopeCompositionByFactor(tcr.view.set, "Epitope.species", top = 10)

# Epitopes (plotly dropdown to filter)

```


```{r mhc}

# MHC group distribution

# MHC counts table

# MHC alleles per group (plotly dropdown to filter)


```


## Complex relationships in TCR:pMHC complexes

```{r vj-sankey}

# V J gene profile sankey diagrams
# Dropdown to filter by epitope, epitope species, MHC group

```


```{r cdr3-length}

# CDR3 alpha and beta lengths
# Dropdown to color by V gene family, J gene family, MHC


```


```{r cdr-clust}

# UMAP coordinates 
# Dropdown to overlay with V genes, J genes, epitope specificity, MHC group


```


```{r cdr3-clust}

# UMAP coordinates 
# Dropdown to overlay with V genes, J genes, epitope specificity, MHC group


```
